LEGAL_SENTENCE_LIST = [
    '''FOR VALUE RECEIVED, the undersigned, (the "Maker"), hereby promises to pay to the order of AWS Bank ("Payee"), the principal sum of $25,000 pursuant to the terms and conditions set forth herein.''',
    '''PAYMENT OF PRINCIPAL. The principal amount of this Promissory Note (the "Note") and any accrued but unpaid interest shall be due and payable in 240 equal monthly installments beginning 11/1/2019. All payments under this Note shall be applied first to accrued but unpaid interest, and next to outstanding principal. If not sooner paid, the entire remaining indebtedness (including accrued interest) shall be due and payable on 11/1/2039.''',
    '''INTEREST. This Note shall bear interest, compounded annually, at 5.25 percent.''',
    '''PREPAYMENT. The Maker shall have the right at any time and from time to time to prepay this Note in whole or in part without premium or penalty.''',
    '''REMEDIES. No delay or omission on part of the holder of this Note in exercising any right hereunder shall operate as a waiver of any such right or of any other right of such holder, nor shall any delay, omission or waiveron any one occasion be deemed a bar to or waiver of the same or any other right on any future occasion. The rights and remedies of the Payee shall be cumulative and may be pursued singly, successively, or together, in the sole discretion of the Payee.''',
    '''EVENTS OF ACCELERATION. The occurrence of any of the following shall constitute an "Event of Acceleration" by Maker under this Note:''',
    '''(a) Maker's failure to pay any part of the principal or interest as and when due under this Note; or''',
    '''(b) Maker's becoming insolvent or not paying its debts as they become due.''',
    '''ACCELERATION. Upon the occurrence of an Event of Acceleration under this Note, and in addition to any other rights and remedies that Payee may have, Payee shall have the right, at its sole and exclusive option, to declare this Note immediately due and payable.''',
    '''SUBORDINATION. The Maker's obligations under this Promissory Note are subordinated to all indebtedness, if any, of Maker, to any unrelated third party lender to the extent such indebtedness is outstanding on the date of this Note and such subordination is required under the loan documents providing for such indebtedness.''',
    '''WAIVERS BY MAKER. All parties to this Note including Maker and any sureties, endorsers, and guarantors hereby waive protest, presentment, notice of dishonor, and notice of acceleration of maturity and agree to continue to remain bound for the payment of principal, interest and all other sums due under this Note notwithstanding any change or changes by way of release, surrender, exchange, modification or substitution of any security for this Note or by way of any extension or extensions of time for the payment of principal and interest; and all such parties waive all and every kind of notice of such change or changes and agree that the same may be made without notice or consent of any of them.''',
    '''EXPENSES. In the event any payment under this Note is not paid when due, the Maker agrees to pay, in addition to the principal and interest hereunder, reasonable attorneys' fees not exceeding a sum equal to 15% of the then outstanding balance owing on the Note, plus all other reasonable expenses incurred by Payee in exercising any of its rights and remedies upon default.''',
    '''GOVERNING LAW. This Note shall be governed by, and construed in accordance with, the laws of the State of Ohio.''',
    '''SUCCESSORS. All of the foregoing is the promise of Maker and shall bind Maker and Maker's successors, heirs and assigns; provided, however, that Maker may not assign any of its rights or delegate any of its obligations hereunder without the prior written consent of the holder of this Note.''',
    '''IN WITNESS WHEREOF, Maker has executed this Promissory Note as of the day and year first above written.''',
]


LEGAL_HEADING_LIST = [
    'BACKGROUND',
    'U.C.C. SECURITY AGREEMENT',
    'SECURITY AGREEMENT',
    'GOVERNING LAW',
    'PROMISE TO PAY',
    'PAYMENT TERMS',
    'LATE PAYMENT TERMS',
    'INTEREST ACCRUAL',
    'PLACE OF PAYMENT',
    'FUNDS OF ESCROW ITEMS',
    'OBLIGATION TO PAY',
    'PAYMENT PRIVILEGES',
    'DISCHARGE',
    'COVENANTS AND WARRANTIES',
    'FIXTURES AND ADDITIONS',
    'NO SALE WITHOUT CONSENT',
    'REQUIRED INSURANCE',
    'GUARANTEE',
    'DEFAULT TERMS',
    'EVENTS OF DEFAULT',
]